### ISSUE TITLE
Special case API for getting the current span

### ISSUE THREAD

**Issue by cartermp** [open-telemetry/opentelemetry-js-api#162]
Today, the way we document getting the current span is to pass in the active context to `getSpan`:

```js
const currentSpan = opentelemetry.trace.getSpan(opentelemetry.context.active());
```

Conceptually, this is seen as one operation, but it's actually two (get the active context, then get the span from that).

Some feedback I've seen from otel-js users is that it'd be nice if they could have a special case API, perhaps like this:

```js
const currentSpan = opentelemetry.trace.getCurrentSpan();
```

I think it's quite common to want whatever the current span is and then do something with it, but less common to want an arbitrary span from an arbitrary context. My interpretation of the spec is that [this should be allowable](https://opentelemetry.io/docs/reference/specification/trace/api/#context-interaction). If so, the `getCurrentSpan` function would be my initial preference, but really anything that shortens the code and requires a single operation, rather than the current 2 operations.

What do you think?

**Comment by Flarna** [comment]
I guess `context.active()` as default in `getSpan`/`setSpan` would fit your needs, like this:
```ts
function getSpan(context = openTelemetry.context.active()): Span | undefined {
  return (context.getValue(SPAN_KEY) as Span) || undefined;
}
```

There are already places (e.g. `startSpan`) where similar defaulting is done instead of adding an extra API.

The only pitfall with such defaulting is that it relies on the global installed context manager. So if user prefers to use a non global one extra care is needed. But I think using non global `ContextManager`, `TracerProvider`,... is anyway exotic outside of tests.

**Comment by cartermp** [comment]
That could probably work. Is there a formal or formal-ish API review process? I'm happy to contribute here but want to make sure the potential solution is considered thoroughly before adding to the public API.

Just some immediate pros/cons for either approach that come to mind:

`getSpan(context = openTelemetry.context.active())`/`setSpan(context = openTelemetry.context.active())`

Pros:

* Similarity with `startSpan` - knowing how any one of these works means you could know the pattern for interacting with the other two
* Less API surface area

Cons:

* Need to learn a default behavior that isn't necessarily apparent based on the name

`getCurrentSpan()`/`setAsCurrentSpan()`

 (choosing an arbitrary name for the inverse of `get` just for symmetry)

Pros:

* Likely obvious what it does based on the name; probably no need to understand default vs. non-default behavior

Cons:

* More API surface area
* Lacks symmetry with other parts of the API by not following a similar default/non-default pattern such as with `startSpan`

**Comment by Flarna** [comment]
The API review process is started by creating an PR here.
You can wait a bit as maybe someone of the maintainers comments here with their opinion which could give a hint which variant is preferred.

**Comment by cartermp** [comment]
Sounds good. I'll create a PR sometime next week if there's no additional feedback and we can take it from there!

**Comment by cartermp** [comment]
Created https://github.com/open-telemetry/opentelemetry-js-api/pull/163 since there's no additional feedback on this issue

**Comment by dyladan** [comment]
Great timing I was just looking at your issue this morning. I think a convenience API for users is a great idea and since it can be implemented entirely in the API by calling other APIs it shouldn't even need any SDK changes. I don't think we have a need for _both_ of these new APIs just to avoid confusing our users, but either of them likely provides enough value to justify.

Personally I would probably rather do `getCurrentSpan` because it does not require changing any existing API which users are already familiar with. Some users may expect `getSpan` to return `undefined` if passed an `undefined` context.

_Originally posted by @dyladan in https://github.com/open-telemetry/opentelemetry-js-api/issues/163#issuecomment-1162065696_

**Comment by cartermp** [comment]
I guess a separate question - would a `setCurrentSpan(span)` API also be desirable? It could similarly just be implemented at the API level as well.

**Comment by Flarna** [comment]
> Some users may expect `getSpan` to return `undefined` if passed an `undefined` context.

But that's not the case it crashes. Similar like calling `api.trace.getCurrentSpan()` crashes now but not after adding the new API.
So if adding a default parameter is seen as breaking adding a new API would be also breaking. But I don't agree to this assessment, I would both mark as non breaking/semver minor.

From symmetry point of view using `getCurrentSpan()` is by far easier as it allows also a `setCurrentSpan(span)`.
Once we go the path for these helpers we should also consider to add `deleteCurrentSpan()`, `getCurrentSpanContext()` and `setCurrentSpanContext()`.

**Comment by Rauno56** [comment]
Not a strong preference honestly, but `getCurrentSpan` makes a tiny bit more sense to me because of the reasons also brought up above by @dyladan.

I feel like we've had extensive discussions that have **not** been so unanimous previously - can someone find those or remember what were the reasons against adding this type of API?

**Comment by dyladan** [comment]
> > Some users may expect `getSpan` to return `undefined` if passed an `undefined` context.
> 
> But that's not the case it crashes. Similar like calling `api.trace.getCurrentSpan()` crashes now but not after adding the new API. So if adding a default parameter is seen as breaking adding a new API would be also breaking. But I don't agree to this assessment, I would both mark as non breaking/semver minor.

I would also say both are non breaking. I was just saying one option is potentially more straightforward for customers to learn and a more obvious interface. Another way to phrase the argument is that I prefer an explicit API (method obviously named) to an implicit one (rely on a default).

> I feel like we've had extensive discussions that have **not** been so unanimous previously - can someone find those or remember what were the reasons against adding this type of API?

A long time ago we discussed adding an API like this and decided not to because it wasn't in the specification and the spec was considering adding these helper methods itself. We didn't want to implement something that conflicted with what the spec eventually added so we decided to wait for spec. Now it's pretty clear that waiting for spec isn't a good idea here.

**Comment by dyladan** [comment]
The way I interpret the spec we already meet the requirements, its just that we lack a more convenient API for the operations.

**Comment by cartermp** [comment]
I won't comment on maintainer toil over time, as I'm not a maintainer, but I very much agree with this:

> Another way to phrase the argument is that I prefer an explicit API (method obviously named) to an implicit one (rely on a default).

Additionally, my experience working with users is that "get the current span" is a very common thing to do as a next step after setting up automatic instrumentation. The general pattern seems to go:

1. Set up automatic instrumentation
2. Get a bunch of value in seeing the full picture of your whole system, even if it's only capturing data at the boundaries of services
3. Identify a handful of services doing lots of meaningful work for your application
4. Get the current span somewhere in a service, attach contextual data from your app, potentially create child spans, and redeploy
5. Continue with (4) until you've got some interesting stuff instrumented and feel like you have sufficient observability such that you don't need to instrument much more

There are various drop-offs in that process, but "get the current span to attach some context from the app" is still pretty common since it's such a (conceptually) lightweight thing to do.

At least in my experience, I've only ever seen people need to _set_ the current span if they're working in a language that makes creating child spans hard, and I've never seen a need for something like `deleteCurrentSpan` or `setCurrentSpanContext`. I think that if those needs come up it's probably okay to just consider them independently from `getCurrentSpan`.

**Comment by vmarchaud** [comment]
I totally see the pattern of progression of users and why they want to have this. However i don't think `getCurrentSpan` is more "explicit" than `getSpan`, i mean in the first place a new user might find equally logic that `getSpan` or `getCurrentSpan` return the current span. 
I'm afraid this might find the user thinking, why is there two method ? What's the difference between `getSpan` and `getCurrentSpan` ? Which would means that we need to explain that `getSpan` to get a span from a specific context and then to explain what's a context (which is IMO the hardest part to understand about the trace implementation).

So i think we should just add a default so that there are no confusion possible. Even instrumentation/sdk writter will most of the time not fetch the span from a non-current context.
I will not block this since other maintainers are far more involved than me and i'm pretty sure this has been discussed at the SIG but i still wanted to give my 2 cents

**Comment by blumamir** [comment]
I really support adding this shortcut syntax. It is so common to get the current active span and the current api makes it too verbose and confusing.

For reference, this is how other languages choose to address this:

### [Ruby](https://github.com/open-telemetry/opentelemetry-ruby/blob/672739120a605c5c14afc48e5aa07d1320443355/api/lib/opentelemetry/trace.rb#L46)
**single api method**
```rb
    # Returns the current span from the current or provided context
    #
    # @param [optional Context] context The context to lookup the current
    #   {Span} from. Defaults to Context.current
    def current_span(context = nil)
      context ||= Context.current
      context.value(CURRENT_SPAN_KEY) || Span::INVALID
    end
```

### [python](https://github.com/open-telemetry/opentelemetry-python/blob/dbcec9f3b143e4de424c16be9ecd19a16be3e630/opentelemetry-api/src/opentelemetry/trace/propagation/__init__.py#L38)
**single api method**
```py
def get_current_span(context: Optional[Context] = None) -> Span:
    """Retrieve the current span.
    Args:
        context: A Context object. If one is not passed, the
            default current context is used instead.
    Returns:
        The Span set in the context if it exists. INVALID_SPAN otherwise.
    """
    span = get_value(_SPAN_KEY, context=context)
    if span is None or not isinstance(span, Span):
        return INVALID_SPAN
    return span
```

### [Java](https://github.com/open-telemetry/opentelemetry-java/blob/51fb582a3604f6a56aef636a6ceaa2d51bc4e165/api/all/src/main/java/io/opentelemetry/api/trace/Span.java#L35)
**2 api methods**
```java
  /**
   * Returns the {@link Span} from the current {@link Context}, falling back to a default, no-op
   * {@link Span} if there is no span in the current context.
   */
  static Span current() {
    Span span = Context.current().get(SpanContextKey.KEY);
    return span == null ? getInvalid() : span;
  }

  /**
   * Returns the {@link Span} from the specified {@link Context}, falling back to a default, no-op
   * {@link Span} if there is no span in the context.
   */
  static Span fromContext(Context context) {
    if (context == null) {
      ValidationUtil.log("context is null");
      return Span.getInvalid();
    }
    Span span = context.get(SpanContextKey.KEY);
    return span == null ? getInvalid() : span;
  }
```

It could have been nice to have this specified in the spec and for all implementations to be aligned, but too late for that now :)

I don't have a strong preference for one option over the other and am ok with whatever will be chosen. 
Thanks for opening this issue and the PR.

**Comment by dyladan** [comment]
At this point I think both proposals solve the problem acceptably. I think `getCurrentSpan` is obvious enough and I'm not particularly worried that users will be confused by the existence of `getSpan` and `getCurrentSpan`. If they are confused, the tsdocs should make it clear quickly.

**Comment by cartermp** [comment]
The biggest gain of adding `getCurrentSpan` is explicitness vs. implicitness. `getCurrentSpan` is obvious in its intent, but a parameterless `getSpan` is not, since it forces you to ask, "which span?". I also think it's worth looking at some precedent here:

* Python uses `trace.get_current_span()` for this special case
* Ruby uses `OpenTelemetry::Trace.current_span`
* .NET uses `Activity.Current` and `Tracer.CurrentSpan` (there are two APIs for .NET tracing...)
* Java uses `Span.current()`
* Rust uses uses `trace::get_active_span(|span| ...)`

Go has no such utility. I've not personally seen feedback from people using these other languages that they're confused about having an API distinct from `getSpan` that gets the current/active span, and also a `getSpan` equivalent for any arbitrary span. I think it might be surprising if JS went a different route with a parameterless `getSpan` with implicit behavior, and certainly wouldn't match what most other languages appear to be doing.

**Comment by vmarchaud** [comment]
I'm okay to go down this route since most have goes this way to keep the consistency but i think other went this route because most early contributors started from opencensus which itself has this concept because of [google choices way back before census](https://github.com/googleapis/cloud-trace-nodejs/blob/main/src/plugin-types.ts#L151).

**Comment by secustor** [comment]
I think this can be closed as https://github.com/open-telemetry/opentelemetry-js-api/pull/163 has been merged.
