### ISSUE TITLE
Add method to get all spans associated with current trace

### ISSUE THREAD

**Issue by MadLittleMods** [open-telemetry/opentelemetry-js-api#167]
Add method to get all spans associated with current trace.

Potential API:
```js
const opentelemetryApi = require('@opentelemetry/api');

// Probably not feasible to keep track of all spans forever and allow getting spans for any traceId
const spans = opentelemetryApi.trace.getSpansForTrace(traceId);

// So only keep track of the spans for the current trace
const spans = opentelemetryApi.trace.getSpansForCurrentTrace();
```

---

The current active context has a span associated with it and each span is associated with a trace by `traceId`. You can get the current `traceId` via this little snippet:
```js
const opentelemetryApi = require('@opentelemetry/api');

const activeCtx = opentelemetryApi.context.active();
const span = opentelemetryApi.trace.getSpan(activeCtx);
const traceId = span.spanContext().traceId;
```

But there is no way to get the rest of the spans associated with that trace or navigate the DAG of spans. If I have the root span, I don't see a way to navigate down the DAG for the child spans since they have child -> parent relationship by `parentSpanId` (and their `traceId`).

To accomplish getting all spans for a trace with the API today, I created a `SpanProcessor` which has access to all spans coming through and it keeps track of all of the spans associated with the trace for the lifetime of an Express route (handled via an Express middleware), https://stackoverflow.com/questions/72973140/get-all-child-spans-associated-with-opentelemetry-trace/73058566

All of this is pretty cumbersome though. It seems like a sane default to keep around the spans for the trace that corresponds to the current active context. The spans can be garbage collected when the active context is no longer in scope.

---

For a use case, my goal is to add a [performance bar](https://github.com/matrix-org/matrix-public-archive/issues/26) to the top of the page served to the client that shows off the slow API requests that happened in the backend. I would like to pull and re-use the data from the OpenTelemetry spans/traces.

**Comment by Flarna** [comment]
A trace is usually distributed across several processes running on different hosts. Therefore it's not possible that a single process provides all the data.

Regarding `getSpansForCurrentTrace`: There is nothing like a "current trace". Usually several operations run in parallel therefore one has several traces in parallel - or no trace at all.

There is no 1:1 connection of context and trace. A context may refer to a span but another context may refer to the same span. tracers consist of several spans. The lifetime of span and context is not bound in general. e.g. it's perfectly valid to have a span not referred to by any context.

I think you should implement your own variant of a SpanProcessor to archive this (at least for the trace part per process). Instead of deleting the spans after exporting you could keep them around as long as you want. I assume you will need some sort of aging to avoid memory leaks because there is no way to detect the end of a trace - you can always get a new request in having the same traceId on a traceparent header.
Also an instrumentation may "forget" to end a span.

**Comment by MadLittleMods** [comment]
> A trace is usually distributed across several processes running on different hosts. Therefore it's not possible that a single process provides all the data.

That's understandable. I didn't quite factor that into my initial thoughts around this. But getting all the data for the current process seems do-able and probably what's most relevant to the process itself to work with anyway. It's all I needed in my use case. And for example, the span representing the hand-off from an app process to a database process would still represent that chunk of time without the sub-span detail. Maybe `opentelemetryApi.trace.getSpansForCurrentTraceInProcess()` is more viable and accurate?

> There is nothing like a "current trace". Usually several operations run in parallel therefore one has several traces in parallel - or no trace at all.

I'm kinda confused by this. At a given spot in code while the process is running, there is only one active context and therefore only one associated trace (the current trace). A context can't refer to more than one span.

While there can be multiple parallel things going on, I assume those would have their own active context if you were to ask for it in those contexts. And it's irrelevant as far as I can tell that some spans aren't referenced by a context. Or that different contexts referring to the same span, it doesn't change anything? Sorry, if I am missing your point here.

It just matters that the active context points to some span because the span is associated with a trace.


---

Good to know that the `SpanProcessor` is the way to go for the time-being 👍 

> you can always get a new request in having the same traceId on a traceparent header.

Interesting! I hadn't heard of `traceparent` before (still new to the OpenTelemetry stuff). Since my app is the top-level consumer facing thing, I've just assumed that each Express request is independent and the trace begins at the start and ends with `res.on('finish', ...)` which is all that is relevant anyway to the user on the timing of the request.

> Also an instrumentation may "forget" to end a span.

That's fine, it's good to know what's still running (no end time).

**Comment by Flarna** [comment]
Yes, right. There is always a current context which may refer to 0 or 1 span. And this span participates in a trace.

regarding traceparent: the [W3C tracecontext spec](https://www.w3.org/TR/trace-context/) describes this in detail. In short you send traceId/spanId/sampling decission serialized (e.g. via HTTP header named traceparent) from one process to another. The receiver uses the received traceId/SpanId to continue the trace.

Even if you have an express app it's not a must that each request starts a root span because you may have OTel in browser and the browser app may decide to create spans and send reuests using a traceparent to your express app whcih continues this trace.

**Comment by MadLittleMods** [comment]
> Even if you have an express app it's not a must that each request starts a root span because you may have OTel in browser and the browser app may decide to create spans and send reuests using a traceparent to your express app whcih continues this trace.

Really good example and appreciate you talking this through!

Even in this case, I only care about the spans within the server app process. Specifically, I was looking to re-use the OpenTelemetry span data for the external API requests made in the backend to explain to the user why it took 60 seconds for us to render the page.

Does `opentelemetryApi.trace.getSpansForCurrentTraceInProcess()` have any viability? Too niche?

**Comment by Flarna** [comment]
Don't expect anything in API regarding this. The API is mostly interface only + dummy implementations. The idea of the API is to just use it in any sort of library (e.g. database drivers,...) without the need to know if there is someone actually recording the spans. Therefore it must be lightweight and efficient.
It's the SDK which creates/exports spans. And the SDK is added once for all in the final app.
If no SDK is installed calls like `startSpan` return dummy objects where e.g. `setAttribute` is a noop.

If you are only interested in finished spans `InMemorySpanExporter` might be close to what you want.
Look at [SimpleSpanProcessor](https://github.com/open-telemetry/opentelemetry-js/blob/main/packages/opentelemetry-sdk-trace-base/src/export/SimpleSpanProcessor.ts) and [InMemorySpanExporter](https://github.com/open-telemetry/opentelemetry-js/blob/v1.4.0/packages/opentelemetry-sdk-trace-base/src/export/InMemorySpanExporter.ts).
[Here](https://github.com/open-telemetry/opentelemetry-js/blob/e39ab883b18636238ef0fd741df4ce5ed53e8d04/experimental/packages/opentelemetry-instrumentation-http/test/functionals/http-enable.test.ts#L63-L65) is a sample in the test which use this.

If you need also in progress spans implement your own SpanProcessor and add an implementation of [`onStart`](https://github.com/open-telemetry/opentelemetry-js/blob/main/packages/opentelemetry-sdk-trace-base/src/export/SimpleSpanProcessor.ts#L48) to record them already after start.

**Comment by MadLittleMods** [comment]
Should this issue be moved to the SDK?

To be clear, I already created a custom `SpanProcessor` which does this [`CaptureSpanProcessor`](https://github.com/matrix-org/matrix-public-archive/blob/fba827a44ea5dc93944534efbe1db2760de23345/server/tracing/capture-span-processor.js), (summarized in https://stackoverflow.com/questions/72973140/get-all-child-spans-associated-with-opentelemetry-trace/73058566)
