### ISSUE TITLE
createContextKey() should use the string as debug information only

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-js-api#39]
The Spec requires that the specified value is used for debugging purposes and does not uniquely identify the key, and it seems `Symbol.for()` (used by this method) returns the same value for the same string at all times.

**Comment by dyladan** [comment]
This is something we had to do because it is possible for multiple versions of the API to be installed in a single `node_modules` directory. If `node_modules/@opentelemetry/api` does `sym = Symbol()` and `node_modules/some-dependency/node_modules/@opentelemetry/api` also does `sym = Symbol()`, then they will have different instances of the symbol and the nested API will not be able to access the global API.

**Comment by dyladan** [comment]
@carlosalberto we're leaning towards closing this with the explanation above unless you have a strong objection?
